### ISSUE TITLE
Thanks and just a few lines of cleanup I added to my copy

### ISSUE THREAD

**Issue by thetick1234567890** [OnyxAzryn/wsl-kernel-updater#1]
Hi,

Thanks for writing this script.  It saved me from looking at that JSON mess posted to update the kernel!  Some programmers need to learn KISS (Keep It Simple Stupid).

Anyway just a few lines I added to my version to clean up version not found error on first run and added details to follow so new kernel is loaded.  It's just a touch and two printfs.

        # Update env
        touch $PACKAGE_DIR/version
        rm $PACKAGE_DIR/version
        echo "$NEWEST_VERSION" >> $PACKAGE_DIR/version
        printf "\n DO NOT KILL WSL2 Window !!!"
        printf "\n wsl.exe --shutdown \n"

**Comment by OnyxAzryn** [comment]
First, you're very welcome and I am glad it has been useful to you.
Second, thank you very much for your contribution. I have added those changes to the script.
